### PR TITLE
made it shorter

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AruMoon** [comment]
This will remove getting user by his id

**Comment by ghost** [comment]
You don't need to get user by id msg.mentionedUsers.first returns a user object
if someone is mentioned in message

**Comment by AruMoon** [comment]
It need, if i don't want ping user

**Comment by ghost** [comment]
Pretty sure that should work if you put a userid for argv[2] or mention them

**Comment by AruMoon** [comment]
Ok, i didn't know about `or` in values

**Pull request merged**
